### ISSUE TITLE
How to use createSelectorCreator with reselect-tools

### ISSUE THREAD

**Issue by samuelcastro** [skortchmark9/reselect-tools#6] opened 2018-03-27 16:25 UTC
I'm creating a custom selector with my own deep equality check like:
```
const createDeepEqualSelector = createSelectorCreator(defaultMemoize, equals);
```
However, it's not clear how to use with with reselect-tools.

**Comment by skortchmark9** [comment] 2018-04-01 07:50
Hey @samuelcastro - this was a pretty obvious feature but I left it out because I haven't been using it in my codebase. The problem is [here](https://github.com/skortchmark9/reselect-tools/blob/0b5ce883c15da88bb55b70a835d04897682bad37/src/index.js#L11). This should default to createSelector and be overridable. For now you can probably just copy it. Don't worry about _allSelectors not being exposed - you can get your selectors into the graph by registering them.

**Comment by samuelcastro** [comment] 2018-04-03 22:29
ok thanks @skortchmark9 I think I will create a fork and implement it, or maybe a PR.

**Comment by skortchmark9** [comment] 2018-07-19 00:38
In version 4.0.0 of reselect, they'll be adding selector dependencies internally, which will mean we no longer need to shim createSelector. If the shim isn't necessary, we won't have this problem any more.

**Comment by djdaniels90** [comment] 2018-10-09 19:29
What is the status of this?  I would like to use it but I need createSelectorCreator functionality?

**Comment by skortchmark9** [comment] 2018-11-05 01:38
Fixed in https://github.com/skortchmark9/reselect-tools/pull/13

**Closed by skortchmark9** 2018-11-05 01:38 UTC
Labels: enhancement
